name: RecycleTable
main: me.mizfit.recycletable.RecycleTable
version: 1.3
api-version: 1.20
softdepend: [GriefPrevention, WorldGuard, Towny, Lands, GriefDefender]
commands:
  giverecycler:
    description: Gives the player a Recycling Table
    usage: /giverecycler
    permission: recycletable.give
  recycletable:
    description: RecycleTable admin commands
    usage: /recycletable reload
    permission: recycletable.admin