name: RecycleTable
main: me.mizfit.recycletable.RecycleTable
version: 1.0
api-version: 1.20
commands:
  giverecycler:
    description: Gives the player a Recycling Table
    usage: /giverecycler
    permission: recycletable.give
